	struct_begin
	struct_field o_Gax2Params_wram, 4
	struct_field o_Gax2Params_wram_size, 4
	struct_field o_Gax2Params_mixing_rate, 2
	struct_field o_Gax2Params_fx_mixing_rate, 2
	struct_field o_Gax2Params_field_C, 2
	struct_field o_Gax2Params_flags, 2
	struct_field o_Gax2Params_num_fx_channels, 2
	struct_field o_Gax2Params_volume, 2
	struct_field o_Gax2Params_unknown, 0x1c @ length depends on versions
	struct_field o_Gax2Params_fx, 4
	struct_field o_Gax2Params_music, 4
	struct_field o_Gax2Params_field_38, 4
	struct_field o_Gax2Params_debug_assert, 1
	struct_field o_Gax2Params_field_3D, 1
	struct_field o_Gax2Params_field_3E, 1
	struct_field o_Gax2Params_field_3F, 1
	struct_field Gax2Params_size, 0
